// All user-facing strings live here. The product language is Korean
// (roadmap stage 1: 한국어 우선). Keep views free of literal copy so the
// wording stays reviewable in one place.

export const strings = {
  appName: '패밀리챗',
  login: {
    title: '가족 계정으로 로그인',
    hint: '가족 관리자가 발급한 계정으로 시작합니다.',
    homeserverLabel: '홈서버 주소',
    homeserverAdvanced: '홈서버 주소 바꾸기 (기본값 사용 중)',
    homeserverPlaceholder: 'https://<homeserver>',
    userLabel: '사용자 이름',
    userPlaceholder: '예: minseo',
    passwordLabel: '비밀번호',
    passwordPlaceholder: '비밀번호',
    submit: '로그인',
    submitting: '접속 중…',
    error: '로그인에 실패했습니다. 주소와 계정을 다시 확인하세요.',
    encryptedNote: '대화는 종단간 암호화되며, 접속 정보는 이 창을 닫으면 지워집니다.',
    deviceName: '패밀리챗 웹',
  },
  rooms: {
    title: '대화',
    loading: '대화 목록을 불러오는 중…',
    empty: '아직 참여한 대화가 없습니다. 가족에게 초대를 요청하세요.',
    syncError: '연결이 끊겼습니다. 자동으로 다시 접속을 시도합니다.',
    familyBadge: '가족방',
    privateBadge: '개인방',
    otherBadge: '다른 방',
    unnamed: '이름 없는 대화',
    memberCount: (n) => `멤버 ${n}명`,
    listTitle: '참여 중인 대화',
    noMessages: '아직 메시지가 없습니다',
    justNow: '방금',
    minutesAgo: (n) => `${n}분 전`,
    hoursAgo: (n) => `${n}시간 전`,
    yesterday: '어제',
    selectHint: '왼쪽 목록에서 대화를 선택하세요.',
  },
  invite: {
    title: '초대',
    from: (name) => `${name}님이 초대했습니다`,
    accept: '수락',
    decline: '거절',
    aiConsentHeading: '이 방에는 AI 참여자가 있습니다',
    aiConsentBody: '이 AI는 이 방을 읽을 수 있으며 답변에 필요한 내용이 제공업체에 전달될 수 있습니다.',
    aiConsentLabel: '이해했으며 동의합니다',
    aiConsentRequired: 'AI 안내에 동의해야 수락할 수 있습니다.',
    failed: '초대 처리에 실패했습니다. 다시 시도하세요.',
    count: (n) => `${n}건`,
  },
  chat: {
    messagePlaceholder: '메시지 입력',
    send: '보내기',
    back: '대화 목록으로',
    attach: '첨부',
    empty: '아직 메시지가 없습니다. 첫 인사를 보내 보세요.',
    newMessages: '새 메시지 ↓',
    attachPhoto: '사진 보내기',
    attachVideo: '영상 보내기',
    attachFile: '파일 보내기',
    encrypted: '이 대화는 종단간 암호화됩니다.',
    encryptedShort: '종단간 암호화',
    sendFailed: '전송에 실패했습니다. 다시 시도하세요.',
    decryptFailed: '메시지를 열 수 없습니다. 이 기기가 아직 암호화 기록을 받지 못했을 수 있습니다.',
    decryptFailedShort: '열 수 없는 메시지',
    unreadable: '표시할 수 없는 메시지입니다.',
    historyLoading: '이전 대화를 불러오는 중…',
    loadEarlier: '이전 대화 불러오기',
    historyStart: '대화의 처음입니다',
    typingOne: (name) => `${name}님이 입력중입니다…`,
    typingMany: (names) => `${names.join(', ')}님이 입력중입니다…`,
  },
  participants: {
    aiBadge: 'AI',
    aiTitle: 'AI 에이전트입니다. 명시적으로 부를 때만 응답합니다.',
    youLabel: '나',
  },
  verification: {
    title: '기기 검증',
    intro: '가족 기기를 검증하면 메시지를 안전하게 주고받을 수 있습니다.',
    start: '이 기기 검증 시작',
    requested: '다른 기기(휴대폰 앱 등)에 검증 요청을 보냈습니다. 그 기기에서 요청을 수락하세요.',
    incomingTitle: '다른 기기에서 검증을 요청했습니다',
    incomingBody: '내 다른 기기가 이 기기를 검증하려고 합니다. 수락하면 두 화면에 같은 이모지가 나타납니다.',
    acceptRequest: '수락하고 시작',
    compareHeading: '두 화면에 같은 이모지가 보이는지 비교하세요.',
    waiting: '상대 기기의 확인을 기다리는 중…',
    same: '네, 같습니다',
    different: '다릅니다',
    done: '기기가 검증되었습니다.',
    mismatchTitle: '이모지가 일치하지 않습니다',
    mismatchBody: '검증을 중단했습니다. 이 기기의 연결이 바뀌었을 수 있습니다. 가족과 직접 확인한 뒤 다시 시도하세요.',
    cancelled: '검증이 취소되었습니다.',
    cancelDetail: (code, by) => `사유: ${code || '알 수 없음'}${by ? ` · 취소한 쪽: ${by}` : ''}`,
    close: '닫기',
  },
  recovery: {
    title: '복구 키',
    intro: '기기를 잃어버려도 복구 키가 있으면 대화 기록을 되찾을 수 있습니다.',
    showOnceHeading: '지금 한 번만 표시됩니다',
    showOnceBody: '이 키를 종이에 적어 가족과 정한 안전한 곳에 보관하세요. 스크린샷이나 메모 앱에 두지 마세요.',
    confirmLabel: '복구 키를 다시 입력해 확인하세요',
    confirmPlaceholder: '복구 키 입력',
    confirm: '확인',
    mismatch: '일치하지 않습니다. 키를 다시 확인하세요.',
    done: '복구 키 확인이 끝났습니다. 이 화면에서는 다시 표시되지 않습니다.',
    privacy: '복구 키는 이 기기 밖으로 전송되지 않습니다. 서버가 수집하지 않습니다.',
  },
  media: {
    photo: '사진',
    video: '영상',
    file: '파일',
    tooLarge: '파일이 너무 큽니다. 최대 90 MB까지 보낼 수 있습니다.',
    unsupported: '이 형식은 아직 지원하지 않습니다.',
  },
  box: {
    title: '보관함',
    toggle: '보관함',
    close: '닫기',
    tabAttachments: '첨부',
    tabFilebox: '파일보관함',
    empty: '아직 받은 첨부가 없습니다. 대화에서 보낸 사진·영상·파일이 여기 모입니다.',
    open: '열기',
    refresh: '새로고침',
    newWindow: '새 창에서 열기',
    loginHint: '처음이면 새 창에서 로그인한 뒤 새로고침하세요.',
    loading: '가져오는 중…',
    downloadFailed: '파일을 가져오지 못했습니다. 다시 시도하세요.',
    previewTitle: '사진 보기',
  },
  menu: {
    open: '설정',
    title: '설정',
  },
  account: {
    logout: '로그아웃',
    logoutConfirm: '이 기기에서 로그아웃할까요? 다시 로그인하려면 비밀번호가 필요합니다.',
    logoutFailed: '로그아웃에 실패했습니다. 연결을 확인하고 다시 시도하세요.',
    devicesTitle: '기기 관리',
    devicesIntro: '이 계정으로 로그인한 기기입니다. 쓰지 않는 기기는 지워서 미서명 세션을 정리하세요.',
    devicesLoading: '기기 목록을 불러오는 중…',
    devicesEmpty: '기기가 없습니다.',
    thisDevice: '이 기기',
    signed: '서명됨',
    unsigned: '미서명',
    unknownSigning: '상태 미확인',
    lastSeen: (when) => `마지막 사용 ${when}`,
    neverSeen: '사용 기록 없음',
    deleteSelected: (n) => `선택한 기기 ${n}개 삭제`,
    passwordLabel: '확인을 위해 비밀번호를 입력하세요',
    passwordPlaceholder: '비밀번호',
    deleteDone: (n) => `기기 ${n}개를 삭제했습니다.`,
    deleteFailed: '기기 삭제에 실패했습니다. 비밀번호를 확인하세요.',
    refresh: '새로고침',
  },
  errors: {
    cryptoUnavailable: '이 기기에서 암호화 모듈을 켜지 못했습니다. 메시지를 보낼 수 없고 새 메시지를 열 수 없습니다. 새로고침하거나 다른 브라우저(사생활 보호 모드 해제)로 다시 시도하세요.',
    plaintextRefused: '암호화되지 않은 전송은 거부되었습니다. 이 방은 암호화가 켜져 있어야 합니다.',
    generic: '문제가 생겼습니다. 잠시 후 다시 시도하세요.',
  },
};

/** True when every leaf string in the table is a non-empty value. */
export function allStringsFilled(node = strings) {
  if (typeof node === 'string') return node.length > 0;
  if (typeof node === 'function') return true;
  return Object.values(node).every(allStringsFilled);
}
