package chat

import (
	"bytes"
	"encoding/json"
	"fmt"
	"testing"
)

func TestMLSContextAdmissionAndNoMutation(t *testing.T) {
	s, a, c, _, call := mlsFixture(t)
	call("owner", "POST", "/v1/rooms", map[string]any{"id": "legacy", "members": []string{"bob"}}, "alice-first", 201)
	call("owner", "GET", "/v1/rooms/legacy/devices", nil, "alice-first", 200)
	call("owner", "GET", "/v1/mls/rooms/legacy/context", nil, "alice-first", 403)
	call("owner", "GET", "/v1/mls/rooms/missing/context", nil, "alice-first", 403)
	call("owner", "POST", "/v1/mls/reservations", map[string]string{"room": "target", "peer_actor": "bob"}, "alice-first", 201)
	path := "/v1/mls/rooms/target/context"
	first := call("owner", "GET", path, nil, "alice-first", 200)
	if !bytes.Equal(first, call("family", "GET", path, nil, "bob-first", 200)) {
		t.Fatal("pair sees different reservation")
	}
	var wire struct {
		Version int      `json:"version"`
		Room    string   `json:"room"`
		Group   string   `json:"group_id"`
		Phase   string   `json:"phase"`
		Pins    []MLSPin `json:"pins"`
	}
	if json.Unmarshal(first, &wire) != nil || wire.Version != 1 || wire.Room != "target" || wire.Group != "" || wire.Phase != "reserved" || len(wire.Pins) != 2 || wire.Pins[0].ID != "alice-first" || wire.Pins[1].ID != "bob-first" {
		t.Fatal("reservation public binding")
	}
	call("family", "GET", path, nil, "alice-first", 403)
	call("outsider", "GET", path, nil, "charlie-first", 403)
	call("owner", "GET", path+"?unexpected=1", nil, "alice-first", 400)
	call("owner", "POST", path, map[string]string{}, "alice-first", 400)
	// Read admission must not enable transport, bind a group, or append a log.
	call("owner", "GET", "/v1/mls/rooms/target/status", nil, "alice-first", 403)
	s.mu.Lock()
	r, err := s.mlsRoom("target")
	s.mu.Unlock()
	if err != nil || r.Group != "" || len(r.Pins) != 0 || r.Next != 1 || r.Phase != "reserved" {
		t.Fatal("read changed reservation", r, err)
	}
	c.Devices[1].Status, c.Devices[1].Revision = "revoked", 2
	if err := a.Replace(c); err != nil {
		t.Fatal(err)
	}
	call("owner", "GET", path, nil, "alice-first", 403)
	call("family", "GET", path, nil, "bob-first", 403)
}

func TestMLSContextBoundRetryAndCorruptReservation(t *testing.T) {
	s, a, c, _, call := mlsFixture(t)
	group := fmt.Sprintf("%032x", 91)
	call("owner", "POST", "/v1/mls/rooms", mlsCreate{"target", group, "alice-first", "bob-first"}, "alice-first", 201)
	path := "/v1/mls/rooms/target/context"
	before := call("owner", "GET", path, nil, "alice-first", 200)
	if !bytes.Contains(before, []byte(`"group_id":"`+group+`"`)) || !bytes.Contains(before, []byte(`"phase":"key-package"`)) {
		t.Fatal("bound context")
	}
	call("family", "POST", "/v1/mls/rooms/target/log", MLSRequest{"kp", "bob-first", group, "key_package", 0, 0, "alice-first", []byte("opaque generated bytes")}, "bob-first", 201)
	if !bytes.Contains(call("family", "GET", path, nil, "bob-first", 200), []byte(`"phase":"welcome"`)) {
		t.Fatal("exact custody retry cannot inspect advanced room")
	}
	call("owner", "POST", "/v1/mls/reservations", map[string]string{"room": "reserved", "peer_actor": "bob"}, "alice-first", 201)
	s.mu.Lock()
	_, err := s.db.Exec("UPDATE mls_rooms SET epoch=4 WHERE room='reserved'")
	s.mu.Unlock()
	if err != nil {
		t.Fatal(err)
	}
	call("owner", "GET", "/v1/mls/rooms/reserved/context", nil, "alice-first", 422)
	c.Devices[0].Status, c.Devices[0].Revision = "revoked", 2
	if err := a.Replace(c); err != nil {
		t.Fatal(err)
	}
	call("family", "GET", path, nil, "bob-first", 403)
}
